set(_CATKIN_CURRENT_PACKAGE "grid_map_filters")
set(grid_map_filters_VERSION "1.6.0")
set(grid_map_filters_MAINTAINER "Péter Fankhauser <pfankhauser@anybotics.com>")
set(grid_map_filters_PACKAGE_FORMAT "2")
set(grid_map_filters_BUILD_DEPENDS "grid_map_core" "grid_map_ros" "grid_map_msgs" "filters")
set(grid_map_filters_BUILD_EXPORT_DEPENDS "grid_map_core" "grid_map_ros" "grid_map_msgs" "filters")
set(grid_map_filters_BUILDTOOL_DEPENDS "catkin")
set(grid_map_filters_BUILDTOOL_EXPORT_DEPENDS )
set(grid_map_filters_EXEC_DEPENDS "grid_map_core" "grid_map_ros" "grid_map_msgs" "filters")
set(grid_map_filters_RUN_DEPENDS "grid_map_core" "grid_map_ros" "grid_map_msgs" "filters")
set(grid_map_filters_TEST_DEPENDS )
set(grid_map_filters_DOC_DEPENDS )
set(grid_map_filters_URL_WEBSITE "http://github.com/ethz-asl/grid_map")
set(grid_map_filters_URL_BUGTRACKER "http://github.com/ethz-asl/grid_map/issues")
set(grid_map_filters_URL_REPOSITORY "")
set(grid_map_filters_DEPRECATED "")