set(_CATKIN_CURRENT_PACKAGE "TrekBot_Main")
set(TrekBot_Main_VERSION "0.0.0")
set(TrekBot_Main_MAINTAINER "nvidia <nvidia@todo.todo>")
set(TrekBot_Main_PACKAGE_FORMAT "2")
set(TrekBot_Main_BUILD_DEPENDS "zed_wrapper")
set(TrekBot_Main_BUILD_EXPORT_DEPENDS "zed_wrapper")
set(TrekBot_Main_BUILDTOOL_DEPENDS "catkin")
set(TrekBot_Main_BUILDTOOL_EXPORT_DEPENDS )
set(TrekBot_Main_EXEC_DEPENDS "zed_wrapper")
set(TrekBot_Main_RUN_DEPENDS "zed_wrapper")
set(TrekBot_Main_TEST_DEPENDS )
set(TrekBot_Main_DOC_DEPENDS )
set(TrekBot_Main_URL_WEBSITE "")
set(TrekBot_Main_URL_BUGTRACKER "")
set(TrekBot_Main_URL_REPOSITORY "")
set(TrekBot_Main_DEPRECATED "")