set(_CATKIN_CURRENT_PACKAGE "grid_map_octomap")
set(grid_map_octomap_VERSION "1.6.0")
set(grid_map_octomap_MAINTAINER "Péter Fankhauser <pfankhauser@anybotics.com>")
set(grid_map_octomap_PACKAGE_FORMAT "2")
set(grid_map_octomap_BUILD_DEPENDS "grid_map_core" "octomap")
set(grid_map_octomap_BUILD_EXPORT_DEPENDS "grid_map_core" "octomap")
set(grid_map_octomap_BUILDTOOL_DEPENDS "catkin")
set(grid_map_octomap_BUILDTOOL_EXPORT_DEPENDS )
set(grid_map_octomap_EXEC_DEPENDS "grid_map_core" "octomap")
set(grid_map_octomap_RUN_DEPENDS "grid_map_core" "octomap")
set(grid_map_octomap_TEST_DEPENDS )
set(grid_map_octomap_DOC_DEPENDS )
set(grid_map_octomap_URL_WEBSITE "http://github.com/ethz-asl/grid_map")
set(grid_map_octomap_URL_BUGTRACKER "http://github.com/ethz-asl/grid_map/issues")
set(grid_map_octomap_URL_REPOSITORY "")
set(grid_map_octomap_DEPRECATED "")