set(_CATKIN_CURRENT_PACKAGE "grid_map_loader")
set(grid_map_loader_VERSION "1.6.0")
set(grid_map_loader_MAINTAINER "Péter Fankhauser <pfankhauser@anybotics.com>")
set(grid_map_loader_PACKAGE_FORMAT "2")
set(grid_map_loader_BUILD_DEPENDS "roscpp" "grid_map_ros" "grid_map_msgs")
set(grid_map_loader_BUILD_EXPORT_DEPENDS "roscpp" "grid_map_ros" "grid_map_msgs")
set(grid_map_loader_BUILDTOOL_DEPENDS "catkin")
set(grid_map_loader_BUILDTOOL_EXPORT_DEPENDS )
set(grid_map_loader_EXEC_DEPENDS "roscpp" "grid_map_ros" "grid_map_msgs")
set(grid_map_loader_RUN_DEPENDS "roscpp" "grid_map_ros" "grid_map_msgs")
set(grid_map_loader_TEST_DEPENDS )
set(grid_map_loader_DOC_DEPENDS )
set(grid_map_loader_URL_WEBSITE "http://github.com/ethz-asl/grid_map")
set(grid_map_loader_URL_BUGTRACKER "http://github.com/ethz-asl/grid_map/issues")
set(grid_map_loader_URL_REPOSITORY "")
set(grid_map_loader_DEPRECATED "")