set(_CATKIN_CURRENT_PACKAGE "grid_map_ros")
set(grid_map_ros_VERSION "1.6.0")
set(grid_map_ros_MAINTAINER "Péter Fankhauser <pfankhauser@anybotics.com>")
set(grid_map_ros_PACKAGE_FORMAT "2")
set(grid_map_ros_BUILD_DEPENDS "roscpp" "grid_map_core" "grid_map_msgs" "grid_map_cv" "sensor_msgs" "nav_msgs" "std_msgs" "geometry_msgs" "cv_bridge" "rosbag" "tf" "visualization_msgs")
set(grid_map_ros_BUILD_EXPORT_DEPENDS "roscpp" "grid_map_core" "grid_map_msgs" "grid_map_cv" "sensor_msgs" "nav_msgs" "std_msgs" "geometry_msgs" "cv_bridge" "rosbag" "tf" "visualization_msgs")
set(grid_map_ros_BUILDTOOL_DEPENDS "catkin")
set(grid_map_ros_BUILDTOOL_EXPORT_DEPENDS )
set(grid_map_ros_EXEC_DEPENDS "roscpp" "grid_map_core" "grid_map_msgs" "grid_map_cv" "sensor_msgs" "nav_msgs" "std_msgs" "geometry_msgs" "cv_bridge" "rosbag" "tf" "visualization_msgs")
set(grid_map_ros_RUN_DEPENDS "roscpp" "grid_map_core" "grid_map_msgs" "grid_map_cv" "sensor_msgs" "nav_msgs" "std_msgs" "geometry_msgs" "cv_bridge" "rosbag" "tf" "visualization_msgs")
set(grid_map_ros_TEST_DEPENDS )
set(grid_map_ros_DOC_DEPENDS )
set(grid_map_ros_URL_WEBSITE "http://github.com/ethz-asl/grid_map")
set(grid_map_ros_URL_BUGTRACKER "http://github.com/ethz-asl/grid_map/issues")
set(grid_map_ros_URL_REPOSITORY "")
set(grid_map_ros_DEPRECATED "")