set(_CATKIN_CURRENT_PACKAGE "zed_video_sub_tutorial")
set(zed_video_sub_tutorial_VERSION "2.6.0")
set(zed_video_sub_tutorial_MAINTAINER "STEREOLABS <support@stereolabs.com>")
set(zed_video_sub_tutorial_PACKAGE_FORMAT "2")
set(zed_video_sub_tutorial_BUILD_DEPENDS "roscpp" "sensor_msgs")
set(zed_video_sub_tutorial_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs")
set(zed_video_sub_tutorial_BUILDTOOL_DEPENDS "catkin")
set(zed_video_sub_tutorial_BUILDTOOL_EXPORT_DEPENDS )
set(zed_video_sub_tutorial_EXEC_DEPENDS "roscpp" "sensor_msgs")
set(zed_video_sub_tutorial_RUN_DEPENDS "roscpp" "sensor_msgs")
set(zed_video_sub_tutorial_TEST_DEPENDS )
set(zed_video_sub_tutorial_DOC_DEPENDS )
set(zed_video_sub_tutorial_URL_WEBSITE "")
set(zed_video_sub_tutorial_URL_BUGTRACKER "")
set(zed_video_sub_tutorial_URL_REPOSITORY "")
set(zed_video_sub_tutorial_DEPRECATED "")