set(_CATKIN_CURRENT_PACKAGE "grid_map_msgs")
set(grid_map_msgs_VERSION "1.6.0")
set(grid_map_msgs_MAINTAINER "Péter Fankhauser <pfankhauser@anybotics.com>")
set(grid_map_msgs_PACKAGE_FORMAT "2")
set(grid_map_msgs_BUILD_DEPENDS "roscpp" "message_generation" "std_msgs" "geometry_msgs")
set(grid_map_msgs_BUILD_EXPORT_DEPENDS "roscpp" "message_generation" "std_msgs" "geometry_msgs")
set(grid_map_msgs_BUILDTOOL_DEPENDS "catkin")
set(grid_map_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(grid_map_msgs_EXEC_DEPENDS "message_runtime" "roscpp" "message_generation" "std_msgs" "geometry_msgs")
set(grid_map_msgs_RUN_DEPENDS "message_runtime" "roscpp" "message_generation" "std_msgs" "geometry_msgs")
set(grid_map_msgs_TEST_DEPENDS )
set(grid_map_msgs_DOC_DEPENDS )
set(grid_map_msgs_URL_WEBSITE "http://github.com/ethz-asl/grid_map")
set(grid_map_msgs_URL_BUGTRACKER "http://github.com/ethz-asl/grid_map/issues")
set(grid_map_msgs_URL_REPOSITORY "")
set(grid_map_msgs_DEPRECATED "")