set(_CATKIN_CURRENT_PACKAGE "TrekBot_Scan")
set(TrekBot_Scan_VERSION "0.0.0")
set(TrekBot_Scan_MAINTAINER "nvidia <nvidia@todo.todo>")
set(TrekBot_Scan_PACKAGE_FORMAT "2")
set(TrekBot_Scan_BUILD_DEPENDS "gazebo_dev" "gazebo_msgs" "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "map_msgs" "move_base_msgs" "python_qt_binding" "qt_dotgraph" "qt_gui" "qt_gui_cpp" "qt_gui_py_common" "qwt_dependency" "rospy" "rviz" "voxel_grid" "zed_wrapper")
set(TrekBot_Scan_BUILD_EXPORT_DEPENDS "gazebo_dev" "gazebo_msgs" "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "map_msgs" "move_base_msgs" "python_qt_binding" "qt_dotgraph" "qt_gui" "qt_gui_cpp" "qt_gui_py_common" "qwt_dependency" "rospy" "rviz" "voxel_grid" "zed_wrapper")
set(TrekBot_Scan_BUILDTOOL_DEPENDS "catkin")
set(TrekBot_Scan_BUILDTOOL_EXPORT_DEPENDS )
set(TrekBot_Scan_EXEC_DEPENDS "gazebo_dev" "gazebo_msgs" "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "map_msgs" "move_base_msgs" "python_qt_binding" "qt_dotgraph" "qt_gui" "qt_gui_cpp" "qt_gui_py_common" "qwt_dependency" "rospy" "rviz" "voxel_grid" "zed_wrapper")
set(TrekBot_Scan_RUN_DEPENDS "gazebo_dev" "gazebo_msgs" "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "map_msgs" "move_base_msgs" "python_qt_binding" "qt_dotgraph" "qt_gui" "qt_gui_cpp" "qt_gui_py_common" "qwt_dependency" "rospy" "rviz" "voxel_grid" "zed_wrapper")
set(TrekBot_Scan_TEST_DEPENDS )
set(TrekBot_Scan_DOC_DEPENDS )
set(TrekBot_Scan_URL_WEBSITE "")
set(TrekBot_Scan_URL_BUGTRACKER "")
set(TrekBot_Scan_URL_REPOSITORY "")
set(TrekBot_Scan_DEPRECATED "")